CREATE DATABASE NADESPENSA;

USE NADESPENSA;

CREATE TABLE USUARIO (
	ID_USUARIO INT PRIMARY KEY NOT NULL,
	SENHA VARCHAR(20) UNIQUE NOT NULL,
	NOME VARCHAR(70) NOT NULL,
);

CREATE TABLE CONTA(
	ID_CONTA INT PRIMARY KEY NOT NULL, --AUTO_INCREMENT
	NOME VARCHAR(30) NOT NULL,
	PRODUTOS VARCHAR(70) NOT NULL,
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),	
	FOREIGN KEY(ID_PRODUTO) REFERENCES ALIMENTO(ID_PRODUTO),
);

CREATE TABLE ALIMENTOS (
	NOME_PRODUTO VARCHAR(30) NOT NULL,
	ID_PRODUTO INT PRIMARY KEY NOT NULL,
	VALIDADE INT UNIQUE NOT NULL,
	QUANTIDADE_PRODUTO INT NOT NULL,
);

CREATE TABLE NOTIFICACAO(
	ID_PRODUTO INT PRIMARY KEY NOT NULL,
	PRODUTOS VARCHAR(70) NOT NULL,
	VALIDADE INT UNIQUE NOT NULL,
	FOREIGN KEY(ID_CONTA) REFERENCES CONTA(ID_CONTA),	
);

CREATE TABLE MERCADO_VIRTUAL(
	PRODUTOS VARCHAR(70) PRIMARY KEY NOT NULL,
	VALIDADE INT UNIQUE NOT NULL,
	USUARIO INT NOT NULL,
	FOREIGN KEY(ID_CONTA) REFERENCES CONTA(ID_CONTA),
);

SELECT * FROM USUARIO;